# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-05-20 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('nombre_encargado', models.CharField(max_length=50)),
                ('comentarios', models.CharField(max_length=500)),
                ('nota_final', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_factor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_indicador', models.CharField(max_length=50)),
                ('factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Factor')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_restaurante', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('nombre_encargado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_factor', models.IntegerField()),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Evaluacion')),
                ('factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Factor')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado_Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_indicador', models.IntegerField()),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Evaluacion')),
                ('indicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Indicador')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='restaurante',
            field=models.ManyToManyField(to='restaurantes.Restaurante'),
        ),
    ]
