# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-05-20 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_auto_20190520_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='nombre_encargado',
            new_name='nombre_inspector',
        ),
    ]
