# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_auto_20190520_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='factor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Factor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado_factor',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Evaluacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado_factor',
            name='factor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Factor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado_indicador',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Evaluacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado_indicador',
            name='indicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Indicador'),
            preserve_default=False,
        ),
    ]
