# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-04 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_auto_20190604_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado_indicador',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado_indicador',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Evaluacion'),
        ),
        migrations.AlterField(
            model_name='resultado_indicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Indicador'),
        ),
    ]
