# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-05-29 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_evaluacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
